name: Analyze and display output on README

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run analyze
        run: yarn run analyze
